version: '3.8'
services:
  afrifurn-mongodb:
    container_name: afrifurn-mongodb
    image: mongo
 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kchikweshe
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      
    networks:
      - afrifurn-network
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  afrifurn-mongo-express:
    container_name: afrifurn-mongo-express
    image: mongo-express
    env_file:
      - ./product-service/.env.production
    ports:
      - 8081:8081
    networks:
      - afrifurn-network
    depends_on:
      - afrifurn-mongodb
  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - afrifurn-network
    ports:
      - 8090:8090
    depends_on:
      - eureka-service
  product-service:
    container_name: afrifurn-product-service
    command: "uvicorn main:app --proxy-headers --port 8000"
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env.production
    ports:
      - 8000:8000
    networks:
      - afrifurn-network
    
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway

  afrifurn-frontend:
    container_name: afrifurn-frontend
    
    build: 
      context: ./afrifurn-frontend
      dockerfile: Dockerfile
      
      args:
        - NEXT_HOST_IP=api-gateway
 
    ports:
      - 3000:3000
    networks:
      - afrifurn-network 
     
  nginx:
    container_name: nginx
    image: nginx:latest
    build: 
      context: ./nginx
    ports:
      - 80:80
    networks:
      - afrifurn-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
 
volumes:
  fastapi:
    driver: local
  mongodb_data_container:
    driver: local

networks:
  afrifurn-network:
    
    


