
services:
  afrifurn-mongodb:
    container_name: afrifurn-mongodb
    build:
      context: ./afrifurn-mongodb
      dockerfile: Dockerfile

    environment:
      - MONGO_INITDB_ROOT_USERNAME=kchikweshe
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    networks:
      - afrifurn-network
    ports:
      - 27017:27017
    volumes:
     
      -  mongodb_data_container:/data

  afrifurn-redis:
    container_name: afrifurn-redis
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass afrifurn_redis_password
    environment:
      - REDIS_PASSWORD=afrifurn_redis_password
    networks:
      - afrifurn-network
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data
    restart: unless-stopped

  afrifurn-mongo-express:
    container_name: afrifurn-mongo-express
    image: mongo-express
    env_file:
      - ./product-service/.env.production
    ports:
      - 8081:8081
    networks:
      - afrifurn-network
    depends_on:
      - afrifurn-mongodb
  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    volumes:
      - /etc/letsencrypt/archive/afri-furn.co.zw:/app/ssl:ro
    
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      
      - SERVER_PORT=8090
    networks:
      - afrifurn-network
    ports:
      - 8090:8090
    volumes:
      - /etc/letsencrypt/archive/afri-furn.co.zw:/app/ssl:ro
    depends_on:
      - eureka-service
  product-service:
    container_name: afrifurn-product-service
    command: "uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000"
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env.production
    environment:
      - REDIS_HOST=afrifurn-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=afrifurn_redis_password
      - REDIS_URL=redis://:afrifurn_redis_password@afrifurn-redis:6379/0
      - REDIS_KEY_PREFIX=afrifurn
      - REDIS_TTL_SECONDS=300
    ports:
      - 8000:8000
    networks:
      - afrifurn-network
    restart: unless-stopped
    
    depends_on:
      - afrifurn-mongodb
      - afrifurn-redis
      - eureka-service
      - api-gateway

  afrifurn-frontend:
    container_name: afrifurn-frontend
    
    build: 
      context: ./afrifurn-frontend
      dockerfile: Dockerfile
      
      args:
        - NEXT_HOST_IP=api-gateway
 
    ports:
      - 3000:3000
    networks:
      - afrifurn-network 
     
  nginx:
    container_name: nginx
    image: nginx:latest
    build: 
      context: ./nginx
    depends_on:
      - api-gateway
      - afrifurn-frontend
      - eureka-service
    ports:
      - 80:80
      - 443:443
    networks:
      - afrifurn-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/afri-furn.co.zw:/etc/nginx/ssl:ro
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot

volumes: 
  fastapi:
    driver: local
  mongodb_data_container:
    driver: local
  redis_data_container:
    driver: local

    

networks:
  afrifurn-network:
    driver: bridge
    


