version: '3.1'
secrets:
  MONGODB_PASSWORD:
    external: true
services:
  afrifurn-mongodb:
    image: mongo
    secrets:
      - MONGODB_PASSWORD
    environment:
      MONGODB_PASSWORD_FILE: /run/secrets/MONGODB_PASSWORD
      MONGO_DB_NAME: afrifurn
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    container_name: afrifurn-mongodb

  afrifurn-mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: afrifurn
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
  

  eureka-service:
    image: kchikweshe/afrifurn-eureka-service  
    ports:
      - 8761:8761
    expose:
      - "8761"
    

  api-gateway-service:
    image: kchikweshe/afrifurn-api-gateway-service
    depends_on:
      - eureka-service  
    ports:
      - 8090:8090
    expose:
      - "8090"
    environment:
      EUREKA_CLIENT_ENABLED: true
      EUREKA_CLIENT_SERVICE_URL: http://eureka-service:8761/eureka
      EUREKA_CLIENT_SERVICE_NAME: afrifurn-eureka-service
    

  service:
    image: kchikweshe/afrifurn-ecommerce-production   # Adjust the path to the Dockerfile
    # restart: always
    ports:
      - 8000:8000
    
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway-service
    environment:
      HOST_IP: ${HOST_IP} 
      EUREKA_CLIENT_ENABLED: true
      EUREKA_CLIENT_SERVICE_URL: http://eureka-service:8761/eureka
      EUREKA_CLIENT_SERVICE_NAME: afrifurn-ecommerce-production
    
 
      

volumes:
  mongodb_data_container:
