version: '3.8'
services:
  afrifurn-mongodb:
    image: mongo
    env_file:
      - ./.env

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - afrifurn-network
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  afrifurn-mongo-express:
    image: mongo-express

    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=afrifurn-mongodb
    networks:
      - afrifurn-network
   
    depends_on:
      - afrifurn-mongodb

  eureka-service:
    image: kchikweshe/afrifurn-eureka-service  
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    env_file:
      - ./.env
    environment:
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - EUREKA_CLIENT_SERVICE_NAME=afrifurn-ecommerce-production
      - HOST_IP=${HOST_IP}
      - EUREKA_HOST=${HOST_IP}


  api-gateway-service:
    image: kchikweshe/afrifurn-api-gateway-service

    ports:
      - 8090:8090
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://5.189.146.192:8761/eureka/
      - EUREKA_CLIENT_SERVICE_NAME=afrifurn-ecommerce-production
      - HOST_IP=5.189.146.192
      - EUREKA_HOST=5.189.146.192
   
    depends_on:
      - eureka-service

  product-service:
    image: kchikweshe/afrifurn-product-service
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - HOST_IP=${HOST_IP}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_CLIENT_ENABLED=${EUREKA_CLIENT_ENABLED}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - EUREKA_CLIENT_SERVICE_NAME=${EUREKA_CLIENT_SERVICE_NAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - afrifurn-network
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway-service

  afrifurn-frontend:
    image: kchikweshe/afrifurn-frontend

    ports:
      - 3000:3000
    
    environment:
      - HOST_IP=${HOST_IP}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_GATEWAY=${NEXT_PUBLIC_API_GATEWAY}
    networks:
      - afrifurn-network  
 
volumes:
  mongodb_data_container:
    driver: local

networks:
  afrifurn-network:
    driver: overlay

