version: '3.8'
services:
  afrifurn-mongodb:
    container_name: afrifurn-mongodb
    image: mongo
 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kchikweshe
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      
    networks:
      - afrifurn-network
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  afrifurn-mongo-express:
    container_name: afrifurn-mongo-express
    image: mongo-express
    env_file:
      - .env.production
    ports:
      - 8081:8081
    

    networks:
      - afrifurn-network
   
    depends_on:
      - afrifurn-mongodb

  eureka-service:
    container_name: eureka-service
    image: kchikweshe/afrifurn-eureka-service  
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    env_file:
      - .env.production


  api-gateway-service:
    container_name: api-gateway
    image: kchikweshe/afrifurn-api-gateway-service
    networks:
      - afrifurn-network
    ports:
      - 8090:8090
    env_file:
      - .env.gateway
    
    depends_on:
      - eureka-service

  product-service:
    container_name: afrifurn-product-service
    image: kchikweshe/afrifurn-product-service
    ports:
      - 8000:8000
    env_file:
      - .env.production
 
    networks:
      - afrifurn-network
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway-service

  afrifurn-frontend:
    container_name: afrifurn-frontend
    
    image: kchikweshe/afrifurn-frontend
    env_file:
      - .env.frontend
    ports:
      - 3000:3000
    networks:
      - afrifurn-network 
     
 
volumes:
  mongodb_data_container:
    driver: local

networks:
  afrifurn-network:
    driver: overlay
    external: true

