
services:
  afrifurn-mongodb:
    container_name: afrifurn-mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kchikweshe
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    networks:
      - afrifurn-network
    ports:
      - 27017:27017
    volumes:
      -  mongodb_data_container:/data/db
      - ./product-service/database/seed/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./product-service/database/seed:/data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    stop_grace_period: 60s
    command: mongod --auth --wiredTigerJournalCompressor=none


  afrifurn-mongo-express:
    container_name: afrifurn-mongo-express
    image: mongo-express
    env_file:
      - ./product-service/.env.production
    ports:
      - 8081:8081
    networks:
      - afrifurn-network
    depends_on:
      - afrifurn-mongodb
  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    volumes:
      - /etc/letsencrypt/archive/afri-furn.co.zw:/app/ssl:ro
    
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      
      - SERVER_PORT=8090
    networks:
      - afrifurn-network
    ports:
      - 8090:8090
    volumes:
      - /etc/letsencrypt/archive/afri-furn.co.zw:/app/ssl:ro
    depends_on:
      - eureka-service
  product-service:
    container_name: afrifurn-product-service
    command: "uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000"
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    env_file:
      - ./product-service/.env.production
    ports:
      - 8000:8000
    networks:
      - afrifurn-network
    restart: unless-stopped
    
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway

  afrifurn-frontend:
    container_name: afrifurn-frontend
    
    build: 
      context: ./afrifurn-frontend
      dockerfile: Dockerfile
      
      args:
        - NEXT_HOST_IP=api-gateway
 
    ports:
      - 3000:3000
    networks:
      - afrifurn-network 
     
  nginx:
    container_name: nginx
    image: nginx:latest
    build: 
      context: ./nginx
    depends_on:
      - api-gateway
      - afrifurn-frontend
      - eureka-service
    ports:
      - 80:80
      - 443:443
    networks:
      - afrifurn-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive/afri-furn.co.zw:/etc/nginx/ssl:ro
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot

volumes: 
  fastapi:
    driver: local
  mongodb_data_container:

    

networks:
  afrifurn-network:
    driver: bridge
    


