version: '3.9'
services:
  afrifurn-mongodb:
    image: mongo
    env_file:
      - ./.env

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


  afrifurn-mongo-express:
    image: mongo-express

    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=afrifurn-mongodb
   
    depends_on:
      - afrifurn-mongodb

  eureka-service:
    image: kchikweshe/afrifurn-eureka-service  

    ports:
      - 8761:8761
    env_file:
      - ./.env
    environment:
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL= http://eureka-service:8761/eureka
      - EUREKA_CLIENT_SERVICE_NAME= afrifurn-ecommerce-production
      - server.port= 8761
      - HOST_IP=localhost
      - EUREKA_HOST= eureka-service


  api-gateway-service:
    image: kchikweshe/afrifurn-api-gateway-service

    ports:
      - 8090:8090
    env_file:
      - ./.env
    environment:
      - EUREKA_CLIENT_ENABLED= true
      - EUREKA_CLIENT_SERVICE_URL= http://eureka-service:8761/eureka
      - EUREKA_CLIENT_SERVICE_NAME= afrifurn-ecommerce-production
      - server.port= 8090
      - HOST_IP= localhost
      - EUREKA_HOST= eureka-service
   
    depends_on:
      - eureka-service

  product-service:
    image: kchikweshe/afrifurn-ecommerce-production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - HOST_IP=${HOST_IP}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_CLIENT_ENABLED=${EUREKA_CLIENT_ENABLED}
      - EUREKA_CLIENT_SERVICE_URL=${EUREKA_CLIENT_SERVICE_URL}
      - EUREKA_CLIENT_SERVICE_NAME=${EUREKA_CLIENT_SERVICE_NAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - CORS_ORIGINS=${CORS_ORIGINS}
 
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway-service

  afrifurn-frontend:
    image: kchikweshe/afrifurn-frontend

    ports:
      - 3000:3000
    
    environment:
      - HOST_IP=${HOST_IP}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_GATEWAY=${NEXT_PUBLIC_API_GATEWAY}
 
volumes:
  mongodb_data_container:
    driver: local

networks:
  afrifurn-network:
    driver: bridge
    attachable: true

