version: '3.1'
secrets:
  MONGODB_PASSWORD:
    external: true
services:
  mongo:
    image: mongo
    secrets:
      - MONGODB_PASSWORD
    environment:
      MONGODB_PASSWORD_FILE: /run/secrets/MONGODB_PASSWORD
      MONGO_DB_NAME: afrifurn
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    container_name: mongodb

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: afrifurn
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
  

  eureka-service:
    image: afrifurn-eureka-service  
    ports:
      - 8761:8761
    

  api-gateway-service:
    image: afrifurn-api-gateway-service
    depends_on:
      - eureka-service  
    ports:
      - 8090:8090
    

  service:
    image: kchikweshe/afrifurn-ecommerce-production   # Adjust the path to the Dockerfile
    # restart: always
    ports:
      - 8000:8000
    
    depends_on:
      - mongo
      - eureka-service
    environment:
      HOST_IP: ${HOST_IP}  # Use the HOST_IP from the .env file
    
 
      

volumes:
  mongodb_data_container:
