version: '3.8'
services:
  afrifurn-mongodb:
    image: mongo
    env_file:
      - ./.env

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - afrifurn-network
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  afrifurn-mongo-express:
    image: mongo-express

    ports:
      - 8081:8081
    env_file:
      - ./.env

    networks:
      - afrifurn-network
   
    depends_on:
      - afrifurn-mongodb

  eureka-service:
    image: kchikweshe/afrifurn-eureka-service  
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    env_file:
      - ./.env


  api-gateway-service:
    image: kchikweshe/afrifurn-api-gateway-service

    ports:
      - 8090:8090
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE_NAME=api-gateway-service
    
   
    depends_on:
      - eureka-service

  product-service:
    image: kchikweshe/afrifurn-product-service
    ports:
      - 8000:8000
    env_file:
      - ./.env
 
    networks:
      - afrifurn-network
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway-service

  afrifurn-frontend:
    image: kchikweshe/afrifurn-frontend

    ports:
      - 3000:3000
    
    env_file:
      - ./.env
    networks:
      - afrifurn-network  
 
volumes:
  mongodb_data_container:
    driver: local

networks:
  afrifurn-network:
    driver: overlay

