version: '3.1'
services:
  mongo:
    image: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
  eureka-service:
    image: afrifurn-eureka-service  
    ports:
      - 8761:8761
  api-gateway-service:
      image: afrifurn-api-gateway-service
      depends_on:
        - eureka-service  
      ports:
        - 8090:8090

  service:
    image: afrifurn-ecommerce-service   # Adjust the path to the Dockerfile
    # restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongo
      - eureka-service
    environment:
      HOST_IP: ${HOST_IP}  # Use the HOST_IP from the .env file
  auth-service:
    image: afrifurn-auth-service   # Adjust the path to the Dockerfile
    # restart: always
    ports:
      - 8002:8002
    depends_on:
      - eureka-service
      - mongo
      

volumes:
  mongodb_data_container:
