version: '3.7'
services:
  afrifurn-mongodb:
    image: mongo
    env_file:
      - ./.env
    networks:
      - afrifurn-network
    environment:
      - MONGO_INITDB_DATABASE= afrifurn
      - MONGO_INITDB_ROOT_USERNAME= admin
      - MONGO_INITDB_ROOT_PASSWORD= mypassword
      - MONGO_DB_NAME= afrifurn
      - MONGO_HOST= 5.189.146.192
      - MONGO_PORT= 27017
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

    container_name: afrifurn-mongodb

  afrifurn-mongo-express:
    image: mongo-express
    networks:
      - afrifurn-network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME= admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD= mypassword
      - ME_CONFIG_MONGODB_SERVER= afrifurn-mongodb
   
    depends_on:
      - afrifurn-mongodb

  eureka-service:
    image: kchikweshe/afrifurn-eureka-service  
    networks:
      - afrifurn-network
    ports:
      - 8761:8761
    env_file:
      - ./.env
    environment:
      - EUREKA_CLIENT_ENABLED= ${EUREKA_CLIENT_ENABLED:-true}
      - EUREKA_CLIENT_SERVICE_URL= http://eureka-service:8761/eureka
      - EUREKA_CLIENT_SERVICE_NAME= afrifurn-ecommerce-production
      - server.port= 8761
      - HOST_IP=5.189.146.192
      - EUREKA_HOST= eureka-service


  api-gateway-service:
    image: kchikweshe/afrifurn-api-gateway-service
    networks:
      - afrifurn-network
    ports:
      - 8090:8090
    env_file:
      - ./.env
    environment:
      - EUREKA_CLIENT_ENABLED= true
      - EUREKA_CLIENT_SERVICE_URL= http://eureka-service:8761/eureka
      - EUREKA_CLIENT_SERVICE_NAME= afrifurn-ecommerce-production
      - server.port= 8090
      - HOST_IP= 5.189.146.192
      - EUREKA_HOST= eureka-service
   
    depends_on:
      - eureka-service

  service:
    image: kchikweshe/afrifurn-ecommerce-production
    networks:
      - afrifurn-network
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - HOST_IP= 5.189.146.192
      - EUREKA_HOST= eureka-service
      - EUREKA_CLIENT_ENABLED= true
      - EUREKA_CLIENT_SERVICE_URL= http://eureka-service:8761/eureka
      - EUREKA_CLIENT_SERVICE_NAME= afrifurn-ecommerce-production
      - MONGODB_PASSWORD= mypassword
      - MONGO_HOST= 5.189.146.192
      - MONGO_PORT= 27017
      - MONGO_DB_NAME= afrifurn
      - MONGO_USER= kchikweshe
      - CORS_ORIGINS= http://5.189.146.192:8090,http://5.189.146.192:3000,http://localhost:8090,http://localhost:3000
 
    depends_on:
      - afrifurn-mongodb
      - eureka-service
      - api-gateway-service

  afrifurn-frontend:
    image: kchikweshe/afrifurn-frontend
    networks:
      - afrifurn-network
    ports:
      - 3000:3000
    
    environment:
      - HOST_IP= 5.189.146.192
      - NEXT_PUBLIC_API_URL= 5.189.146.192
      - NEXT_PUBLIC_API_GATEWAY= http://5.189.146.192:8090/api/v1
 
volumes:
  mongodb_data_container:
    driver: local

networks:
  afrifurn-network:
    driver: overlay

