spring:
  application:
    name: api-gateway

  cloud:
    gateway:  
      globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: 
              - "https://docs.spring.io"
              - "http://www.afri-furn.co.zw:3000"
              allowedHeaders: '*'
              maxAge: 30
              allowedMethods:
              - GET
              - POST
              
            
      routes:
        - id: product-service
          uri: http://product-service:8000
          predicates:
            - Path=/product-service/api/v1/**
        - id: auth-service
          uri: http://auth-service:8002
          predicates:
            - Path=/auth/api/v1/**
        - id: order-service
          uri: http://order-service:8004
          predicates:
            - Path=/orders/api/v1/** 
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true

# CORS configuration for external access
cors:
  allowed-origins: http://afrifurn.co.zw:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
